### ISSUE TITLE
在移动端加载时 页面头部会出现coverDiv内容闪烁 

### ISSUE THREAD

**Issue by webylb** [channg/EasyLazyload.js#4]

**Comment by channg** [comment]
延迟加载的蒙层会在手机端滑动的时候出现不可控的布局异常,可以将 showTime 设置为1 快速显示元素.

**Comment by webylb** [comment]
这个问题 我试着showTime 设置为1 , 或者去掉蒙层 还是会有闪烁 
但在pc端不会

**Comment by channg** [comment]
@webylb 建议修改源码处理，因为源码只有150行，应该很容易修改为你想要的

**Comment by webylb** [comment]
算是找个一个解决方法吧    调整了meng-lazy-div的样式z-index值
